-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdzukupEMGkIDTmMo
8C3WIYs5LVLmx8FMegSnbB4mWHKgCgYIKoZIzj0DAQehRANCAASoBzqMeg7TJoQr
sl7sTZj7+c+6cu3hS1AZJfIbkM8QyCVVNwArgqIMvcxkKgOzBm27Lhn5lJyyYp3Y
Ul98bwDp
-----END PRIVATE KEY-----