/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as NuevaClaveRouteImport } from './routes/nueva-clave'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as ComercioRouteImport } from './routes/comercio'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnirseSlugRouteImport } from './routes/unirse.$slug'
import { Route as ReservaTokenRouteImport } from './routes/reserva.$token'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaClaveRoute = NuevaClaveRouteImport.update({
  id: '/nueva-clave',
  path: '/nueva-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercioRoute = ComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnirseSlugRoute = UnirseSlugRouteImport.update({
  id: '/unirse/$slug',
  path: '/unirse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaTokenRoute = ReservaTokenRouteImport.update({
  id: '/reserva/$token',
  path: '/reserva/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comercio': typeof ComercioRoute
  '/hotel': typeof HotelRoute
  '/login': typeof LoginRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/planes': typeof PlanesRoute
  '/p/$slug': typeof PSlugRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/unirse/$slug': typeof UnirseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comercio': typeof ComercioRoute
  '/hotel': typeof HotelRoute
  '/login': typeof LoginRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/planes': typeof PlanesRoute
  '/p/$slug': typeof PSlugRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/unirse/$slug': typeof UnirseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comercio': typeof ComercioRoute
  '/hotel': typeof HotelRoute
  '/login': typeof LoginRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/planes': typeof PlanesRoute
  '/p/$slug': typeof PSlugRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/unirse/$slug': typeof UnirseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comercio'
    | '/hotel'
    | '/login'
    | '/nueva-clave'
    | '/planes'
    | '/p/$slug'
    | '/reserva/$token'
    | '/unirse/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comercio'
    | '/hotel'
    | '/login'
    | '/nueva-clave'
    | '/planes'
    | '/p/$slug'
    | '/reserva/$token'
    | '/unirse/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comercio'
    | '/hotel'
    | '/login'
    | '/nueva-clave'
    | '/planes'
    | '/p/$slug'
    | '/reserva/$token'
    | '/unirse/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComercioRoute: typeof ComercioRoute
  HotelRoute: typeof HotelRoute
  LoginRoute: typeof LoginRoute
  NuevaClaveRoute: typeof NuevaClaveRoute
  PlanesRoute: typeof PlanesRoute
  PSlugRoute: typeof PSlugRoute
  ReservaTokenRoute: typeof ReservaTokenRoute
  UnirseSlugRoute: typeof UnirseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-clave': {
      id: '/nueva-clave'
      path: '/nueva-clave'
      fullPath: '/nueva-clave'
      preLoaderRoute: typeof NuevaClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercio': {
      id: '/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof ComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unirse/$slug': {
      id: '/unirse/$slug'
      path: '/unirse/$slug'
      fullPath: '/unirse/$slug'
      preLoaderRoute: typeof UnirseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/$token': {
      id: '/reserva/$token'
      path: '/reserva/$token'
      fullPath: '/reserva/$token'
      preLoaderRoute: typeof ReservaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComercioRoute: ComercioRoute,
  HotelRoute: HotelRoute,
  LoginRoute: LoginRoute,
  NuevaClaveRoute: NuevaClaveRoute,
  PlanesRoute: PlanesRoute,
  PSlugRoute: PSlugRoute,
  ReservaTokenRoute: ReservaTokenRoute,
  UnirseSlugRoute: UnirseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
