/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComercioRouteImport } from './routes/comercio'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnirseSlugRouteImport } from './routes/unirse.$slug'
import { Route as GymMemberIdRouteImport } from './routes/gym.$memberId'
import { Route as GymReferirCodeRouteImport } from './routes/gym-referir.$code'
import { Route as GymNotificationsProgramIdRouteImport } from './routes/gym-notifications.$programId'
import { Route as GymInscribirseSlugRouteImport } from './routes/gym-inscribirse.$slug'
import { Route as GymAdminProgramIdRouteImport } from './routes/gym-admin.$programId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercioRoute = ComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnirseSlugRoute = UnirseSlugRouteImport.update({
  id: '/unirse/$slug',
  path: '/unirse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GymMemberIdRoute = GymMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => GymRoute,
} as any)
const GymReferirCodeRoute = GymReferirCodeRouteImport.update({
  id: '/gym-referir/$code',
  path: '/gym-referir/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GymNotificationsProgramIdRoute =
  GymNotificationsProgramIdRouteImport.update({
    id: '/gym-notifications/$programId',
    path: '/gym-notifications/$programId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GymInscribirseSlugRoute = GymInscribirseSlugRouteImport.update({
  id: '/gym-inscribirse/$slug',
  path: '/gym-inscribirse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GymAdminProgramIdRoute = GymAdminProgramIdRouteImport.update({
  id: '/gym-admin/$programId',
  path: '/gym-admin/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comercio': typeof ComercioRoute
  '/login': typeof LoginRoute
  '/gym-admin/$programId': typeof GymAdminProgramIdRoute
  '/gym-inscribirse/$slug': typeof GymInscribirseSlugRoute
  '/gym-notifications/$programId': typeof GymNotificationsProgramIdRoute
  '/gym-referir/$code': typeof GymReferirCodeRoute
  '/gym/$memberId': typeof GymMemberIdRoute
  '/unirse/$slug': typeof UnirseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comercio': typeof ComercioRoute
  '/login': typeof LoginRoute
  '/gym-admin/$programId': typeof GymAdminProgramIdRoute
  '/gym-inscribirse/$slug': typeof GymInscribirseSlugRoute
  '/gym-notifications/$programId': typeof GymNotificationsProgramIdRoute
  '/gym-referir/$code': typeof GymReferirCodeRoute
  '/gym/$memberId': typeof GymMemberIdRoute
  '/unirse/$slug': typeof UnirseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comercio': typeof ComercioRoute
  '/login': typeof LoginRoute
  '/gym-admin/$programId': typeof GymAdminProgramIdRoute
  '/gym-inscribirse/$slug': typeof GymInscribirseSlugRoute
  '/gym-notifications/$programId': typeof GymNotificationsProgramIdRoute
  '/gym-referir/$code': typeof GymReferirCodeRoute
  '/gym/$memberId': typeof GymMemberIdRoute
  '/unirse/$slug': typeof UnirseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comercio'
    | '/login'
    | '/gym-admin/$programId'
    | '/gym-inscribirse/$slug'
    | '/gym-notifications/$programId'
    | '/gym-referir/$code'
    | '/gym/$memberId'
    | '/unirse/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comercio'
    | '/login'
    | '/gym-admin/$programId'
    | '/gym-inscribirse/$slug'
    | '/gym-notifications/$programId'
    | '/gym-referir/$code'
    | '/gym/$memberId'
    | '/unirse/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comercio'
    | '/login'
    | '/gym-admin/$programId'
    | '/gym-inscribirse/$slug'
    | '/gym-notifications/$programId'
    | '/gym-referir/$code'
    | '/gym/$memberId'
    | '/unirse/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComercioRoute: typeof ComercioRoute
  LoginRoute: typeof LoginRoute
  GymAdminProgramIdRoute: typeof GymAdminProgramIdRoute
  GymInscribirseSlugRoute: typeof GymInscribirseSlugRoute
  GymNotificationsProgramIdRoute: typeof GymNotificationsProgramIdRoute
  GymReferirCodeRoute: typeof GymReferirCodeRoute
  UnirseSlugRoute: typeof UnirseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercio': {
      id: '/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof ComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unirse/$slug': {
      id: '/unirse/$slug'
      path: '/unirse/$slug'
      fullPath: '/unirse/$slug'
      preLoaderRoute: typeof UnirseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/$memberId': {
      id: '/gym/$memberId'
      path: '/$memberId'
      fullPath: '/gym/$memberId'
      preLoaderRoute: typeof GymMemberIdRouteImport
      parentRoute: typeof GymRoute
    }
    '/gym-referir/$code': {
      id: '/gym-referir/$code'
      path: '/gym-referir/$code'
      fullPath: '/gym-referir/$code'
      preLoaderRoute: typeof GymReferirCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-notifications/$programId': {
      id: '/gym-notifications/$programId'
      path: '/gym-notifications/$programId'
      fullPath: '/gym-notifications/$programId'
      preLoaderRoute: typeof GymNotificationsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-inscribirse/$slug': {
      id: '/gym-inscribirse/$slug'
      path: '/gym-inscribirse/$slug'
      fullPath: '/gym-inscribirse/$slug'
      preLoaderRoute: typeof GymInscribirseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-admin/$programId': {
      id: '/gym-admin/$programId'
      path: '/gym-admin/$programId'
      fullPath: '/gym-admin/$programId'
      preLoaderRoute: typeof GymAdminProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComercioRoute: ComercioRoute,
  LoginRoute: LoginRoute,
  GymAdminProgramIdRoute: GymAdminProgramIdRoute,
  GymInscribirseSlugRoute: GymInscribirseSlugRoute,
  GymNotificationsProgramIdRoute: GymNotificationsProgramIdRoute,
  GymReferirCodeRoute: GymReferirCodeRoute,
  UnirseSlugRoute: UnirseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
